namespace: "marsa"
email: "your-email@example.com"
postgres:
  marsaUserPassword: "marsa-password"
  adminPassword: "postgres-admin-password"
  storageSize: "2Gi"
tls:
  enabled: true
  domain: "marsa.gomaa.ovh"
