apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsa-web
  labels:
    app: marsa-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marsa-web
  template:
    metadata:
      labels:
        app: marsa-web
    spec:
      containers:
      - name: marsa-web
        image: "ghcr.io/marsa-cloud/marsa-web:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        env:
        - name: API_UPSTREAM
          value: "http://marsa-api:3000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsa-api
  labels:
    app: marsa-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marsa-api
  template:
    metadata:
      labels:
        app: marsa-api
    spec:
      serviceAccountName: marsa-api
      containers:
      - name: marsa-api
        image: "ghcr.io/marsa-cloud/marsa-api:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: marsa-config
        - secretRef:
            name: marsa-api-secrets
        env:
        - name: MARSA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: MARSA_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://marsa:$(MARSA_PASSWORD)@postgres:5432/marsa"
