apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: marsa-web
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
  selector:
    app: marsa-web

---
apiVersion: v1
kind: Service
metadata:
  name: marsa-api
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 3000
  selector:
    app: marsa-api